version: "3"

services:
  web:
    container_name: nginx
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/www:ro
    ports:
      - 80:80

  deploy-webhook:
    container_name: demo-pycsw-org-deploy-webhook
    image: geopython/demo.pycsw.org-deploy-webhook
    build: deploy-webhook

  pycsw:
    container_name: demo-pycsw-org-cite
    image: geopython/pycsw:latest
    volumes:
      - ./pycsw/cite/cite.cfg:/etc/pycsw/pycsw.cfg:ro
    environment:
     - SCRIPT_NAME=/cite/csw
