version: "3"

services:
  web:
    container_name: nginx
    image: nginx:alpine
    restart: always
    depends_on:
      - pycsw-cite
      - pycsw-gisdata
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/www:ro
    ports:
      - 80:80

  deploy-webhook:
    container_name: demo-pycsw-org-deploy-webhook
    image: geopython/demo.pycsw.org-deploy-webhook
    build: deploy-webhook

  pycsw-cite:
    container_name: demo-pycsw-org-cite
    image: geopython/pycsw:latest
    volumes:
      - ./pycsw/cite/cite.cfg:/etc/pycsw/pycsw.cfg:ro
    environment:
     - SCRIPT_NAME=/cite

  pycsw-gisdata:
    container_name: demo-pycsw-org-gisdata
    image: geopython/pycsw:latest
    volumes:
      - ./pycsw/gisdata/gisdata.cfg:/etc/pycsw/pycsw.cfg:ro
      - ./pycsw/gisdata/gisdata.db:/home/pycsw/gisdata/gisdata.db:ro
    environment:
     - SCRIPT_NAME=/gisdata
